### ISSUE TITLE
compute canada cvmfs-client role configuration

### ISSUE THREAD

**Issue by WandrilleD** [scicore-unibas-ch/ansible-playbook-scicore-courses-cloud#10]
Hi, 
the default configuration on the ansible-cvmfs-client role (from https://github.com/cvmfs-contrib/ansible-cvmfs-client.git)
does not configure the computecanada stack properly (errors during deployments + not possible to load modules in the resulting cluster).

This is fixed simply by uncommenting line 10 of the role config file : ansible/roles/ansible-cvmfs-client/defaults/main.yml
I do it with :
`sed 's/#  - \"cvmfs-config-computecanada\"/  - \"cvmfs-config-computecanada\"/g' ansible/roles/ansible-cvmfs-client/defaults/main.yml`

But I am not sure how you want to document this.
Best.

**Comment by pescobar** [comment]
I think the right approach would be to override this var in your config. e.g. add something like this to ` config/slurm_cluster_switch_cloud.yml`

```
cvmfs_configuration:
#  - "cvmfs-config-default"
  - "cvmfs-config-computecanada"
```

**Comment by pescobar** [comment]
I just realised it's maybe better to update this ansible task https://github.com/scicore-unibas-ch/ansible-playbook-scicore-courses-cloud/blob/master/ansible/tasks/compute_canada.yml#L16-L21  like this


```
- name: Configure the CVMFS client to access the ComputeCanada soft stack
  import_role:
    name: ansible-cvmfs-client
  vars:
    cvmfs_client_configure_storage: false
    cvmfs_http_proxy: "DIRECT"
    cvmfs_configuration:
      - "cvmfs-config-computecanada"
```
